project:
  type: website
  output-dir: docs
  
  render:
    - "*.qmd"
  
website:
  search: false
  navbar:
    background: "#ffffff"
    left:
      - text: "Nigel Gray"
        href: index.qmd 
    
    right:
      - about.qmd
      - research.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true